name: Publish to Typst Universe

on:
  release:
    types: [published]

jobs:
  publish:
    uses: leonieziechmann/typst-nix-utils/.github/workflows/publish-package.yaml@main
    with:
      fork_repo: leonieziechmann/packages
      files: "typst.toml lib.typ src LICENSE README.md"
    secrets:
      packages_pat: ${{ secrets.PACKAGES_PAT }}
